- hosts: localhost
  vars:
    #domain: "helloworld.com"
    #ansible_user: "ec2-user"
    #ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    com: trak
    env: test
    app: front
    project: trak
    domain: trakapptest.es
    path: var
    PASS_DB: "{{ lookup('env','PASS_DB') }}"
    USER_DB: "{{ lookup('env','USER_DB') }}"
    NAME_DB: "{{ lookup('env','NAME_DB') }}"
    HOST_DB: "{{ lookup('env','HOST_DB') }}"
    PORT_DB: "{{ lookup('env','PORT_DB') }}"
    #pass_db: {{ pass_db_user | vault() }}
  become: yes
  tasks:

  - name: install postgresql
    yum:
      name: 
        - postgresql
        - postgresql-server
        - postgresql-contrib
        - postgresql-libs
      state: present

  - name: Check if PostgreSQL is initialized
    stat:
      path: "/var/lib/pgsql/data/pg_hba.conf"
    register: postgres_data

  - name: Initialize PostgreSQL
    shell: "postgresql-setup initdb"
    when: not postgres_data.stat.exists

  - name: copy pg_hba.conf
    template:
        src: pg_hba-trust.conf
        dest: /var/lib/pgsql/data/pg_hba.conf
        backup: yes
        owner: root
        group: root
        mode: '0644'

  - name: start postgres
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: copy script create db
    template:
        src: create-database-test.sql
        dest: /tmp/db-test.sql
        owner: root
        group: root
        mode: '0644'

  - name: Create db y user
    shell: |
      cat /tmp/db-test.sql > /tmp/db
      cat /tmp/db-test.sql | sudo -u postgres psql
      rm /tmp/db-test.sql