- hosts: localhost
  vars:
    var-name: foo
  become: yes
  tasks:
  - name: configure ansible
    template:
        src: ansible-conf.cfg
        dest: /etc/ansible/ansible.cfg
        backup: yes
        owner: root
        group: root
        mode: '0644'