- hosts: localhost
  strategy: debug
  vars:
    #ansible_user: "ec2-user"
    #ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    com: trak
    env: test
    app: back
    project: apptest
    domain: apptest.es
    path: tmp
    urlgit: https://github.com/icasadosar/
    branch: main
    pathlog: /var/log/trak
  become: yes
  tasks:
  - name: debug start playbook
    debug:
      msg: "start: ansible-playbook django.yml"

  - name: install package repo epel form amazon linux 2
    shell: "amazon-linux-extras install epel -y"

  - name: yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: install compiler
    yum:
      name:
        - gcc-c++
        - make
      state: present
     
  - name: install python
    yum:
      name: 
        - python3
        - python3-pip
      state: present

  - name: create log directory
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}
      state: directory
      mode: '0775'

  - name: create error-log file
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}/error-{{ app }}.{{ domain }}-http-80.log
      state: touch
      mode: u=rw,g=r,o=r

  - name: create access-log file
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}/access-{{ app }}.{{ domain }}-http-80.log
      state: touch
      mode: u=rw,g=r,o=r       

#  - name: install nodejs
#    yum:
#      name: ['nodejs']
#      skip_broken: yes
#      state: present

#  - name: install npm
#    yum:
#      name: ['npm']
#      skip_broken: yes
#      state: present

  - name: git-clone repo
    git:
      repo: "{{ urlgit }}/{{ app }}"
      dest: "/{{ path }}/{{ project }}/{{ app }}"
      #single_branch: yes
      version: "{{ branch }}"
      
  - name: install python requeriments
    pip:
      requirements: "/{{ path }}/{{ project }}/{{ app }}/requirements.txt"
      executable: pip3
    #notify: restart nodejs

  - name: copy nginx site-{{ app }}
    template:
        src: site-{{ app }}-{{ domain }}-http-80.conf
        dest: /etc/nginx/conf.d/{{ app }}.{{ domain }}-http-80.conf
        owner: root
        group: root
        mode: '0644'
    notify: restart nginx

  - name: install supervisord
    yum:
      name: supervisor
      state: present

  - name: copy supervisord supervisord-gunicorn.ini
    template:
        src: supervisord-gunicorn.ini
        dest: /etc/supervisord.d/gunicorn.ini
        owner: root
        group: root
        mode: '0644'
    notify: restart supervisord

  - name: create directory log {{ pathlog }}
    file:
       path: "{{ pathlog }}"
       state: directory
       mode: '0775'
       owner: root
       group: root

  - name: create directory /op/trak
    file:
       path: /opt/trak
       state: directory
       mode: '0775'
       owner: root
       group: root

  - name: copy startup script to /opt directory
    template:
        src: doStartupDjango.sh
        dest: /opt/trak/doStartupDjango.sh
        mode: 0755

  - name: Run startup script
    shell: /opt/trak/doStartupDjango.sh > {{ pathlog }}/doStartupDjango.log 2> {{ pathlog }}/doStartupDjango.err.log & sleep 1
    args:
      chdir: /{{ path }}/{{ project }}/{{ app }}
    #async: 45
    #poll: 0
  
  - name: debug end playbook
    debug:
      msg: "end: ansible-playbook django.yml"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart supervisord
      service: 
        name: supervisord
        state: restarted