- hosts: localhost
  vars:
    #ansible_user: "ec2-user"
    #ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    domain: trakFront.test.apptrak.es
  become: yes
  tasks:
  - name: Enable nginx form amazon linux 2
    shell: "amazon-linux-extras enable nodejs"

  - name: yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: install nodejs
    yum:
      name: ['nodejs']
      state: present

  - name: git-clone repo trakFront
    git:
      repo: https://github.com/traksl/trakFront
      dest: /tmp/apptest/trakFront
      single_branch: yes
      version: pruebas-ci

  - name: install nodejs packages on packages.json
    npm:
      path: /tmp/apptest/trakFront
      state: present
    notify: restart nodejs

  - name: copy nginx site-trakFront
    template:
        src: site-trakFront-http-80.conf
        dest: /etc/nginx/conf.d/{{ domain }}-http-80.conf
        owner: root
        group: root
        mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    
    - name: restart nodejs
      command: npm restart
 