- hosts: localhost
  vars:
    #ansible_user: "ec2-user"
    #ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    com: trak
    env: test
    app: front
    project: apptest
    domain: apptest.es
    path: tmp
    urlgit: https://github.com/icasadosar/
    branch: main 
  become: yes
  tasks:
  - name: install package repo epel form amazon linux 2
    shell: "amazon-linux-extras install epel -y"

  - name: yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: install compiler
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: install node from repo
    shell: "sudo curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -"
     
  - name: install nodejs
    yum:
      name: nodejs
      state: present

  - name: create log directory
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}
      state: directory
      mode: '0775'

  - name: create error-log file
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}/error-{{ app }}.{{ domain }}-http-80.log
      state: touch
      mode: u=rw,g=r,o=r

  - name: create access-log file
    file:
      path: /var/log/nginx/{{ domain }}/{{ app }}/access-{{ app }}.{{ domain }}-http-80.log
      state: touch
      mode: u=rw,g=r,o=r      

#  - name: install nodejs
#    yum:
#      name: ['nodejs']
#      skip_broken: yes
#      state: present

#  - name: install npm
#    yum:
#      name: ['npm']
#      skip_broken: yes
#      state: present

  - name: git-clone repo
    git:
      repo: "{{ urlgit }}/{{ app }}"
      dest: "/{{ path }}/{{ project }}/{{ app }}"
      #single_branch: yes
      version: "{{ branch }}"
      
  - name: install nodejs packages on packages.json
    npm:
      path: "/{{ path }}/{{ project }}/{{ app }}"
      state: present
    #notify: restart nodejs

  - name: copy nginx site-{{ app }}
    template:
        src: site-{{ app }}-{{ domain }}-http-80.conf
        dest: /etc/nginx/conf.d/{{ app }}.{{ domain }}-http-80.conf
        owner: root
        group: root
        mode: '0644'
    notify: restart nginx

  - name: create directory /op/trak
    file:
       path: /opt/trak
       state: directory
       mode: '0775'
       owner: root
       group: root

  - name: copy startup script to /opt directory
    template:
        src: doStartupNodejs.sh
        dest: /opt/trak/doStartupNodejs.sh
        mode: 0755

  - name: Run startup script
    shell: /opt/trak/doStartupDjango.sh > /tmp/doStartupNodejs.log 2> /tmp/doStartupNodejs.err.log & # sleep 1
    args:
      chdir: /{{ path }}/{{ project }}/{{ app }}
    #async: 45
    #poll: 0 

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

#    - name: restart nodejs
      #command: cd /{{ path }}/{{ project }}/{{ app }} && nohup npm restart --prefix /{{ path }}/{{ project }}/{{ app }} > stdout.txt 2> stderr.txt &
#      command: npm restart &
      #command: /usr/bin/forever start /{{ path }}/{{ project }}/{{ app }}/src/sw-build.js
      # /tmp/apptest/front/node_modules/react-scripts/scripts/start.js
      #shell: /bin/bash doNodejs.sh start &
#      args:
#        chdir: /{{ path }}/{{ project }}/{{ app }}