- hosts: localhost
  vars:
    #ansible_user: "ec2-user"
    #ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    env: test
    app: front
    project: apptest
    domain: apptest.es
    path: tmp
    urlgit: https://github.com/icasadosar/
    branch: main 
  become: yes
  tasks:
  - name: install package repo epel form amazon linux 2
    shell: "amazon-linux-extras install epel -y"

  - name: yum update
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
    register: yum_update_status

  - name: install compiler
    yum:
      name:
        - gcc-c++
        - make
      state: present

  - name: install node from repo
    shell: "curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -"
     
  - name: install nodejs
    yum:
      name: nodejs
      state: present

  - name: create log directory
    file:
      path: /var/log/nginx/{{ domain }}
      state: directory
      mode: '0775'
      owner: nginx
      group: nginx

  - name: create log file
    file:
      path: 
        - /var/log/nginx/error-{{ domain }}-http-80.log
        - /var/log/nginx/access-{{ domain }}-http-80.log
      state: touch
      mode: '0644'
      owner: nginx
      group: nginx

#  - name: install nodejs
#    yum:
#      name: ['nodejs']
#      skip_broken: yes
#      state: present

#  - name: install npm
#    yum:
#      name: ['npm']
#      skip_broken: yes
#      state: present

  - name: git-clone repo
    git:
      repo: "{{ urlgit }}/{{ app }}"
      dest: "{{ path }}/{{ project }}/{{ app }}"
      #single_branch: yes
      version: "{{ branch }}"

  - name: install nodejs packages on packages.json
    npm:
      path: "{{ path }}/{{ project }}/{{ app }}"
      state: present
    notify: restart nodejs

  - name: copy nginx site-{{ app }}
    template:
        src: site-{{ app }}-{{ domain }}-http-80.conf
        dest: /etc/nginx/conf.d/{{ app }}.{{ env }}.{{ domain }}-http-80.conf
        owner: root
        group: root
        mode: '0644'
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart nodejs
      command: npm restart